# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  command:  # id of input
    description: 'cdk command'
    required: true
    #default: 'World'
outputs:
#  time: # id of output
#    description: 'The time we greeted you'
    version:
        description: 'The version of CDK'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
