# action.yml
name: 'CDK action'
description: 'CDK action'
inputs:
  command:  # id of input
    description: 'cdk subcommand'
    required: true
outputs:
    ouptut:
        description: 'The command output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
