on:
#  schedule:
#    - cron: 0 6 * * *
  workflow_dispatch: {}

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: version
      id: version
      uses: pahud/awscdk-action@20ec874
      with:
        command: '--version'
    - name: diff
      id: diff
      uses: pahud/awscdk-action@20ec874
      with:
        command: 'diff'
    - name: Get the output time
      run: echo "The version was ${{ steps.version.outputs.version }}"
