name: CDK
on:
  workflow_dispatch: {}

jobs:
  cdk_job:
    runs-on: ubuntu-latest
    name: AWS CDK demo jobs
    steps:
    - name: version
      id: version
      uses: pahud/awscdk-action@v0.1.0
      with:
        command: '--version'
#     - name: diff
#       id: diff
#       uses: pahud/awscdk-action@v0.1.0
#       with:
#         command: 'diff'
